sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/7c1a69342b5a192a3670"
    on_success: change
    on_failure: always
    on_start: false
